In [2]:
import numpy as np
import pandas as pd

In [3]:
fd = pd.read_csv("iris1.data")

In [4]:
fd = fd.drop("Spicies", axis=1)
irisNumpy = np.array(fd, dtype=np.float64)
irisNumpy[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [5]:
print("Dimension of the irisNumpy Array is --> ", irisNumpy.ndim)
print("Shape of the irisNumpy Array is --> ", irisNumpy.shape)
print("Size of the irisNumpy Array is --> ", irisNumpy.size)
print("Itemsize of the irisNumpy Array is --> ", irisNumpy.itemsize)
print("Total memory size of the irisNumpy Array is --> ", irisNumpy.itemsize * irisNumpy.size)
print("DataType of the irisNumpy Array is --> ", irisNumpy.dtype)
print("Name of the DataType of the irisNumpy Array is --> ", irisNumpy.dtype.name)
print("Type of the irisNumpy Array is --> ", type(irisNumpy))

('Dimension of the irisNumpy Array is --> ', 2)
('Shape of the irisNumpy Array is --> ', (150, 4))
('Size of the irisNumpy Array is --> ', 600)
('Itemsize of the irisNumpy Array is --> ', 8)
('Total memory size of the irisNumpy Array is --> ', 4800)
('DataType of the irisNumpy Array is --> ', dtype('float64'))
('Name of the DataType of the irisNumpy Array is --> ', 'float64')
('Type of the irisNumpy Array is --> ', <type 'numpy.ndarray'>)


In [11]:
zerosNumpy = np.zeros((5,3), dtype=np.int64)
print("This is a zero matrix --> ", zerosNumpy)

('This is a zero matrix --> ', array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]]))


In [12]:
onesNumpy = np.ones((5,3), dtype = np.float32)
print("This is a matrix of ones --> ", onesNumpy)

('This is a matrix of ones --> ', array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32))


In [13]:
idenNumpy = np.eye(5)
print("This is a identity matrix --> ", idenNumpy)
idenNumpy = np.identity((4), dtype=np.int64)
print("This is a identity matrix with different method and Datatype int64 --> ", idenNumpy)

('This is a identity matrix --> ', array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]]))
('This is a identity matrix with different method and Datatype int64 --> ', array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]]))


In [14]:
randNumpy = np.random.random((3,5))
print("This is a random matrix --> ")
print(randNumpy)

This is a random matrix --> 
[[0.46173894 0.83798983 0.88780599 0.69856356 0.24124661]
 [0.11869275 0.16963306 0.9348862  0.30229169 0.76318578]
 [0.52648096 0.78900859 0.52798782 0.94979932 0.40029403]]


In [15]:
randNumpy = np.random.uniform(-5, 5, (3,5))
print("This is a random matrix uniformly distributed between -5 to 5--> ")
print(randNumpy)

This is a random matrix uniformly distributed between -5 to 5--> 
[[-0.41717061 -2.44630862  2.90671507 -2.2376776  -4.3708618 ]
 [-3.25111594 -3.42044967  1.78248707  3.43716574 -4.9117011 ]
 [ 4.83920182 -3.68999328  2.30789184  0.51323102  1.21173671]]


Sine Values:

In [16]:
x = np.linspace(-10, 10, 51)
x

array([-10. ,  -9.6,  -9.2,  -8.8,  -8.4,  -8. ,  -7.6,  -7.2,  -6.8,
        -6.4,  -6. ,  -5.6,  -5.2,  -4.8,  -4.4,  -4. ,  -3.6,  -3.2,
        -2.8,  -2.4,  -2. ,  -1.6,  -1.2,  -0.8,  -0.4,   0. ,   0.4,
         0.8,   1.2,   1.6,   2. ,   2.4,   2.8,   3.2,   3.6,   4. ,
         4.4,   4.8,   5.2,   5.6,   6. ,   6.4,   6.8,   7.2,   7.6,
         8. ,   8.4,   8.8,   9.2,   9.6,  10. ])

In [17]:
x = np.arange(-10, 10.05, 0.3)
x

array([-10. ,  -9.7,  -9.4,  -9.1,  -8.8,  -8.5,  -8.2,  -7.9,  -7.6,
        -7.3,  -7. ,  -6.7,  -6.4,  -6.1,  -5.8,  -5.5,  -5.2,  -4.9,
        -4.6,  -4.3,  -4. ,  -3.7,  -3.4,  -3.1,  -2.8,  -2.5,  -2.2,
        -1.9,  -1.6,  -1.3,  -1. ,  -0.7,  -0.4,  -0.1,   0.2,   0.5,
         0.8,   1.1,   1.4,   1.7,   2. ,   2.3,   2.6,   2.9,   3.2,
         3.5,   3.8,   4.1,   4.4,   4.7,   5. ,   5.3,   5.6,   5.9,
         6.2,   6.5,   6.8,   7.1,   7.4,   7.7,   8. ,   8.3,   8.6,
         8.9,   9.2,   9.5,   9.8])

In [35]:
sine = np.sin(x)
import matplotlib.pyplot as plt
plt.plot(x,sine)
plt.show()

In [36]:
quad1 = x**2 + 2*x + 5
plt.plot(x, quad1)
plt.show()

In [37]:
def norm_function(x, mean, var):
    return 1.0/((2.0*np.pi*var**2)**0.5) * np.exp(-(x-mean)**2/(2*(var**2)))

x = np.arange(-5, 5.01, 0.05)
pdf1 = norm_function(x, 0, 0.2)
pdf2 = norm_function(x, 0, 0.4)
pdf3 = norm_function(x, 0, 0.8)
pdf4 = norm_function(x, -2, 5.0)
plt.plot(x, pdf1, color='blue', label = "mean = {} var = {}".format(0, 0.2))
plt.plot(x, pdf2, color='red', label = "mean = {} var = {}".format(0, 1.0))
plt.plot(x, pdf3, color='brown', label = "mean = {} var = {}".format(0, 4.0))
plt.plot(x, pdf4, color='green', label = "mean = {} var = {}".format(-2, 5.0))
plt.legend()
plt.show()

In [52]:
x = np.linspace(-4, 4, 9)
print("Value of x --> ", x)
y = np.linspace(-5, 5, 11)
print("Value of y --> ", y)

('Value of x --> ', array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.]))
('Value of y --> ', array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.]))


In [53]:
xx, yy = np.meshgrid(x, y)
print("Value of xx --> ")
print(xx)
print
print("Shape of xx Matrix --> ", np.shape(xx))
print
print
print("Value of yy --> ")
print(yy)
print
print("Shape of yy Matrix --> ", np.shape(yy))

Value of xx --> 
[[-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]]

('Shape of xx Matrix --> ', (11, 9))


Value of yy --> 
[[-5. -5. -5. -5. -5. -5. -5. -5. -5.]
 [-4. -4. -4. -4. -4. -4. -4. -4. -4.]
 [-3. -3. -3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.]]

('Shape of yy Matrix --> ', (11, 9))


In [54]:
elipse = xx**2.0 + 4*yy**2
plt.contourf(xx, yy, elipse, cmap='jet')
plt.colorbar()
plt.show()

In [55]:
random_data = np.random.random((11,9))
plt.contourf(xx, yy, random_data, cmap='jet')
plt.colorbar()
plt.show()

In [66]:
xx1, yy1 = np.meshgrid(x, y, indexing='ij')
print("Value of xx1 --> ")
print(xx1)
print
print("Value of yy1 --> ")
print(yy1)

Value of xx1 --> 
[[-4. -4. -4. -4. -4. -4. -4. -4. -4. -4. -4.]
 [-3. -3. -3. -3. -3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]]

Value of yy1 --> 
[[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]]


In [65]:
np.all(xx == xx1.T)
np.all(yy == yy1.T)

True

In [4]:
L = [1,2,3,4]
print(L)
A = np.array([1,2,3,4])
print(A)

[1, 2, 3, 4]
[1 2 3 4]


In [7]:
for e in L:
    print e
    
print   

for e in A:
    print e

1
2
3
4

1
2
3
4


In [12]:
L.append(5)
L = L + [6]
print L
print
# A.append(5)
A = A + [6]
print A

[1, 2, 3, 4, 5, 5, 5, 5, 6, 5, 6]

[ 7  8  9 10]


In [17]:
2*L
2*A
np.sqrt(A)
np.log(A)

array([1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [21]:
a = np.array([1,2])
b = np.array([2,1])
print(a, b)
zip(a, b)

(array([1, 2]), array([2, 1]))


[(1, 2), (2, 1)]

In [24]:
dot = 0
for e, f in zip(a, b):
    dot+=e*f
dot

4

In [39]:
print(a*b)
a*b


[2 2]
4
4
4


In [40]:
print(np.sum(a*b))
print ((a*b).sum())
print(a.dot(b))

4
4
4
