In [132]:
import numpy as np
import pandas as pd

In [133]:
fd = pd.read_csv("iris1.data")

In [134]:
fd = fd.drop("Spicies", axis=1)
irisNumpy = np.array(fd, dtype=np.float64)
irisNumpy[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [135]:
print("Dimension of the irisNumpy Array is --> ", irisNumpy.ndim)
print("Shape of the irisNumpy Array is --> ", irisNumpy.shape)
print("Size of the irisNumpy Array is --> ", irisNumpy.size)
print("Itemsize of the irisNumpy Array is --> ", irisNumpy.itemsize)
print("Total memory size of the irisNumpy Array is --> ", irisNumpy.itemsize * irisNumpy.size)
print("DataType of the irisNumpy Array is --> ", irisNumpy.dtype)
print("Name of the DataType of the irisNumpy Array is --> ", irisNumpy.dtype.name)
print("Type of the irisNumpy Array is --> ", type(irisNumpy))

('Dimension of the irisNumpy Array is --> ', 2)
('Shape of the irisNumpy Array is --> ', (150, 4))
('Size of the irisNumpy Array is --> ', 600)
('Itemsize of the irisNumpy Array is --> ', 8)
('Total memory size of the irisNumpy Array is --> ', 4800)
('DataType of the irisNumpy Array is --> ', dtype('float64'))
('Name of the DataType of the irisNumpy Array is --> ', 'float64')
('Type of the irisNumpy Array is --> ', <type 'numpy.ndarray'>)


In [136]:
zerosNumpy = np.zeros((5,3), dtype=np.int64)
print("This is a zero matrix --> ", zerosNumpy)

('This is a zero matrix --> ', array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]]))


In [137]:
onesNumpy = np.ones((5,3), dtype = np.float32)
print("This is a matrix of ones --> ", onesNumpy)

('This is a matrix of ones --> ', array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32))


In [138]:
idenNumpy = np.eye(5)
print("This is a identity matrix --> ", idenNumpy)
idenNumpy = np.identity((4), dtype=np.int64)
print("This is a identity matrix with different method and Datatype int64 --> ", idenNumpy)

('This is a identity matrix --> ', array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]]))
('This is a identity matrix with different method and Datatype int64 --> ', array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]]))


In [139]:
randNumpy = np.random.random((3,5))
print("This is a random matrix --> ")
print(randNumpy)

This is a random matrix --> 
[[0.3153573  0.41452263 0.56077943 0.06872864 0.08875582]
 [0.38355712 0.25160974 0.19333141 0.19063286 0.37072813]
 [0.85049972 0.37303794 0.43792461 0.319449   0.27965523]]


In [140]:
randNumpy = np.random.uniform(-5, 5, (3,5))
print("This is a random matrix uniformly distributed between -5 to 5--> ")
print(randNumpy)

This is a random matrix uniformly distributed between -5 to 5--> 
[[ 1.13170538 -0.11760412  0.71591919 -2.2250787  -2.1995844 ]
 [ 2.9838243   0.25274125  1.86655921  3.58351381  2.94524963]
 [-2.67898582  2.60345723  3.37374932  0.71934885  1.24030925]]


Sine Values:

In [141]:
x = np.linspace(-10, 10, 51)
x

array([-10. ,  -9.6,  -9.2,  -8.8,  -8.4,  -8. ,  -7.6,  -7.2,  -6.8,
        -6.4,  -6. ,  -5.6,  -5.2,  -4.8,  -4.4,  -4. ,  -3.6,  -3.2,
        -2.8,  -2.4,  -2. ,  -1.6,  -1.2,  -0.8,  -0.4,   0. ,   0.4,
         0.8,   1.2,   1.6,   2. ,   2.4,   2.8,   3.2,   3.6,   4. ,
         4.4,   4.8,   5.2,   5.6,   6. ,   6.4,   6.8,   7.2,   7.6,
         8. ,   8.4,   8.8,   9.2,   9.6,  10. ])

In [142]:
x = np.arange(-10, 10.05, 0.3)
x

array([-10. ,  -9.7,  -9.4,  -9.1,  -8.8,  -8.5,  -8.2,  -7.9,  -7.6,
        -7.3,  -7. ,  -6.7,  -6.4,  -6.1,  -5.8,  -5.5,  -5.2,  -4.9,
        -4.6,  -4.3,  -4. ,  -3.7,  -3.4,  -3.1,  -2.8,  -2.5,  -2.2,
        -1.9,  -1.6,  -1.3,  -1. ,  -0.7,  -0.4,  -0.1,   0.2,   0.5,
         0.8,   1.1,   1.4,   1.7,   2. ,   2.3,   2.6,   2.9,   3.2,
         3.5,   3.8,   4.1,   4.4,   4.7,   5. ,   5.3,   5.6,   5.9,
         6.2,   6.5,   6.8,   7.1,   7.4,   7.7,   8. ,   8.3,   8.6,
         8.9,   9.2,   9.5,   9.8])

In [156]:
sine = np.sin(x)
import matplotlib.pyplot as plt
plt.plot(x,sine)
plt.show()

In [157]:
quad1 = x**2 + 2*x + 5
plt.plot(x, quad1)
plt.show()

In [ ]:
def norm_function(x, mean, var):
    return 1.0/((2.0*np.pi*var**2)**0.5) * np.exp(-(x-mean)**2/(2*(var**2)))

x = np.arange(-5, 5.01, 0.05)
pdf1 = norm_function(x, 0, 0.2)
pdf2 = norm_function(x, 0, 0.4)
pdf3 = norm_function(x, 0, 0.8)
pdf4 = norm_function(x, -2, 5.0)
plt.plot(x, pdf1, color='blue', label = "mean = {} var = {}".format(0, 0.2))
plt.plot(x, pdf2, color='red', label = "mean = {} var = {}".format(0, 1.0))
plt.plot(x, pdf3, color='brown', label = "mean = {} var = {}".format(0, 4.0))
plt.plot(x, pdf4, color='green', label = "mean = {} var = {}".format(-2, 5.0))
plt.legend()
plt.show()